version: '3'
services:
  app:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=0000
      - DB_NAME=work_work
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=work_work