version: '3'
services:
  server:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - database
    links:
      - database
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=work_work

  client:
    build: ./frontend
    ports:
      - '3000:3000'

  database:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: work_work
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
